/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolicitudesMant;

import BD.Conn;
import Class.SOLICITUDES;
import Class.ingreso_solicitudes;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class FINALIZAR_SOLICITUD extends javax.swing.JInternalFrame {

    int no;
    int depto;
    int estatus;
    int estado;
    int idincidencia;
    String fechainicion;
    String fechafin;
            
    

    /**
     * Creates new form Programar
     */
    public FINALIZAR_SOLICITUD() {
        initComponents();
        CODIGO.requestFocus();
        ListaSolicitudes();
    }

    public void llenarmaquina() {
        try {
            idincidencia = Integer.parseInt(String.valueOf(Solicitud.getModel().getValueAt(Solicitud.getSelectedRow(), 0)));
            SOLICITUDES p = ingreso_solicitudes.buscarMaquinaActualizar(Integer.parseInt(String.valueOf(Solicitud.getModel().getValueAt(Solicitud.getSelectedRow(), 0))));
            DESCRIPCION.setText(p.getDescripcion());
            MODELO.setText(p.getModelo());
            SN.setText(p.getSerie());
            FABRICANTE.setText(p.getFabricante());
            NOTA.setText(p.getNotadefalla());
            DEPARTAMENTO.setText(p.getDeparta());
            FECHASOLICITUD.setText(p.getFecha1());
            NOTAFIN.setText(p.getNotas());

        } catch (Exception e) {
            System.out.println("Error de Seleccion:" + e);
        }
    }

    public void fecha() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/YY HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        FECHASOLICITUD.setText(dateFormat.format(cal.getTime()));
        AGREGAR.requestFocus();
    }

    public void limpiar() {
        DESCRIPCION.setText("");
        MODELO.setText("");
        SN.setText("");
        FABRICANTE.setText("");
        NOTA.setText("");
        FECHASOLICITUD.setText("");
        DEPARTAMENTO.setText("");
        CODIGO.setText("");
        CODIGO.requestFocus();
        ESTATUS.setSelectedItem("SELECCIONAR...");
        fecha.setDate(null);
        NOTA.setText("");
        AGREGAR.setEnabled(false);
        fecha.setEnabled(false);
        NOTAFIN.setEnabled(false);
        NOTAFIN.setText("");
    }
  
    public void actualizarServicio(){
    
       try {
            Connection con = Conn.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("update incidencias set estatus = "+estatus+",fecha_inicio ='"+fechainicion+"',notas = '"+NOTAFIN.getText()+"'  where no_incidencias ="+idincidencia);
            rs.close();
            stmt.close();
            con.close();
        } catch (SQLException error) {
            System.out.print(error + " ERROR QUE OBTIENE EL ULTIMO ID DE INGRESO ");
        }
    }
    
   public void actualizarServicioFin(){
    
       try {
            Connection con = Conn.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("update incidencias set estatus = "+estatus+",fecha_cerrado ='"+fechafin+"',estado = 2,notas = '"+NOTAFIN.getText()+"'  where no_incidencias ="+idincidencia);
            rs.close();
            stmt.close();
            con.close();
        } catch (SQLException error) {
            System.out.print(error + " ERROR QUE OBTIENE EL ULTIMO ID DE INGRESO ");
        }   
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DESCRIPCION = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MODELO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FABRICANTE = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NOTA = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        DEPARTAMENTO = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        FECHASOLICITUD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Solicitud = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        AGREGAR = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NOTAFIN = new javax.swing.JTextArea();
        ESTATUS = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CODIGO = new javax.swing.JTextField();

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("FECHA DE MANTENIMIENTO");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SOLICITUDES DE SERVICIO");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DESCRIPCION");

        DESCRIPCION.setEditable(false);
        DESCRIPCION.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DESCRIPCION.setForeground(new java.awt.Color(0, 102, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("MODELO");

        MODELO.setEditable(false);
        MODELO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MODELO.setForeground(new java.awt.Color(0, 102, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("S/N");

        SN.setEditable(false);
        SN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SN.setForeground(new java.awt.Color(0, 102, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("FABRICANTE");

        FABRICANTE.setEditable(false);
        FABRICANTE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FABRICANTE.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(MODELO, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DESCRIPCION, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FABRICANTE, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DESCRIPCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DESCRIPCION DE LA FALLA");

        NOTA.setEditable(false);
        NOTA.setColumns(20);
        NOTA.setLineWrap(true);
        NOTA.setRows(5);
        jScrollPane1.setViewportView(NOTA);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("DEPARTAMENTO");

        DEPARTAMENTO.setEditable(false);
        DEPARTAMENTO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("FECHA  SOLICITUD");

        FECHASOLICITUD.setEditable(false);
        FECHASOLICITUD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FECHASOLICITUD.setForeground(new java.awt.Color(255, 0, 0));
        FECHASOLICITUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FECHASOLICITUDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(FECHASOLICITUD)
                    .addComponent(DEPARTAMENTO)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DEPARTAMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FECHASOLICITUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        Solicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "DEPARTAMENTO", "FALLA", "ESTADO"
            }
        ));
        Solicitud.setSelectionBackground(new java.awt.Color(255, 255, 153));
        Solicitud.setSelectionForeground(new java.awt.Color(0, 0, 0));
        Solicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SolicitudMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Solicitud);

        AGREGAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AGREGAR.setText("ACTUALIZAR");
        AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGARActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("ESTATUS");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("FECHA");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("NOTA");

        NOTAFIN.setColumns(20);
        NOTAFIN.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NOTAFIN.setLineWrap(true);
        NOTAFIN.setRows(5);
        jScrollPane3.setViewportView(NOTAFIN);

        ESTATUS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ESTATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR...", "ESPERANDO REPUESTOS", "EN PROCESO", "TERMINADA" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ESTATUS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ESTATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(AGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CODIGO");

        CODIGO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CODIGO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CODIGOKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGARActionPerformed

        if (NOTAFIN.getText().compareTo("") != 0 && !ESTATUS.getSelectedItem().toString().equalsIgnoreCase("SELECCIONAR...")) {
            
            if (ESTATUS.getSelectedItem().toString().equalsIgnoreCase("ESPERANDO REPUESTOS")) {
                estatus = 3;
                Date date = fecha.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                fechainicion = sdf.format(date);
                actualizarServicio();
                ListaSolicitudes();
                limpiar();
                
            } else if (ESTATUS.getSelectedItem().toString().equalsIgnoreCase("EN PROCESO")) {
                estatus=2;
                Date date = fecha.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                fechainicion = sdf.format(date);
                actualizarServicio();
                ListaSolicitudes();
                limpiar();
            } else if (ESTATUS.getSelectedItem().toString().equalsIgnoreCase("TERMINADA")) {
                estatus = 4;
                Date date = fecha.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                fechafin = sdf.format(date);
                actualizarServicioFin();
                ListaSolicitudes();
                limpiar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
        }
    }//GEN-LAST:event_AGREGARActionPerformed
    private void FECHASOLICITUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FECHASOLICITUDMouseClicked
        AGREGAR.requestFocus();
    }//GEN-LAST:event_FECHASOLICITUDMouseClicked

    private void CODIGOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CODIGOKeyReleased
        ListaSolicitudes();
    }//GEN-LAST:event_CODIGOKeyReleased

    private void SolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolicitudMouseClicked
        AGREGAR.setEnabled(true);
        fecha.setEnabled(true);
        NOTAFIN.setEnabled(true);
        llenarmaquina();
        
    }//GEN-LAST:event_SolicitudMouseClicked

    private void ListaSolicitudes() {

        ArrayList<SOLICITUDES> result1 = ingreso_solicitudes.ListarSolicitudes();
        recargarTable(result1);
    }

    public void recargarTable(ArrayList<SOLICITUDES> list) {
        Object[][] datos1 = new Object[list.size()][6];
        int i = 0;
        for (SOLICITUDES p : list) {
            datos1[i][0] = p.getId_incidencia();
            datos1[i][1] = p.getCodigo();
            datos1[i][2] = p.getDescripcion();
            datos1[i][3] = p.getDeparta();
            datos1[i][4] = p.getNotadefalla();
            datos1[i][5] = p.getEstado();
            i++;
        }
        Solicitud.setModel(new javax.swing.table.DefaultTableModel(
                datos1,
                new String[]{
                    "NO.", "CODIGO", "DESCRIPCION", "DEPARTAMENTO", "FALLA", "ESTADO"
                }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        TableColumn columna1 = Solicitud.getColumn("NO.");
        columna1.setPreferredWidth(0);
        TableColumn columna2 = Solicitud.getColumn("DESCRIPCION");
        columna2.setPreferredWidth(200);
        TableColumn columna3 = Solicitud.getColumn("DEPARTAMENTO");
        columna3.setPreferredWidth(0);
        TableColumn columna4 = Solicitud.getColumn("FALLA");
        columna4.setPreferredWidth(200);
        TableColumn columna5 = Solicitud.getColumn("ESTADO");
        columna5.setPreferredWidth(50);
        TableColumn columna6 = Solicitud.getColumn("CODIGO");
        columna6.setPreferredWidth(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FINALIZAR_SOLICITUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FINALIZAR_SOLICITUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FINALIZAR_SOLICITUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FINALIZAR_SOLICITUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FINALIZAR_SOLICITUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR;
    private javax.swing.JTextField CODIGO;
    private javax.swing.JTextField DEPARTAMENTO;
    private javax.swing.JTextField DESCRIPCION;
    private javax.swing.JComboBox<String> ESTATUS;
    private javax.swing.JTextField FABRICANTE;
    private javax.swing.JTextField FECHASOLICITUD;
    private javax.swing.JTextField MODELO;
    private javax.swing.JTextArea NOTA;
    private javax.swing.JTextArea NOTAFIN;
    private javax.swing.JTextField SN;
    private javax.swing.JTable Solicitud;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
